# Environment variables to be defined in the build configuration:
# AUTH0_TEST_CLIENT_ID = Client id to use in test
# AUTH0_TEST_DOMAIN = Domain to use in test
# AUTH0_TEST_AUDIENCE = API Audience to use in test

# Jobs and Workflows
version: 2.1
parameters:
  machine_image:
    type: string
    default: ubuntu-2004:202201-02
orbs:
  node: circleci/node@3.0.0
jobs:
  checkout:
    machine:
      image: << pipeline.parameters.machine_image >>
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  sample-01:
    machine:
      image: << pipeline.parameters.machine_image >>
    environment:
      - AUTH0_CFG: Sample-01/auth_config.json
      - AUTH0_EXAMPLE_CFG: Sample-01/auth_config.json.example
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Replace Auth0 test credentials
          command: |
            sed \
              -e "s/AUTH0_DOMAIN/$AUTH0_TEST_DOMAIN/g" \
              -e "s/AUTH0_CLIENT_ID/$AUTH0_TEST_CLIENT_ID/g" \
              -e "s/AUTH0_API_IDENTIFIER/$AUTH0_TEST_API_IDENTIFIER/g" \
              $AUTH0_EXAMPLE_CFG > $AUTH0_CFG
      - node/install-packages:
          pkg-manager: npm
          app-dir: Sample-01
      - run:
          name: Run unit tests
          working_directory: Sample-01
          command: npm run test:ci
workflows:
  version: 2
  quickstarts_login:
    jobs:
      - checkout:
          context: Quickstart SPA Test
      - sample-01:
          context: Quickstart SPA Test
          requires:
            - checkout
